/*
 * This source file was generated by the Gradle 'init' task
 */
package src;

public class App {
    public static void main(String[] args) {

        // 묵시적 형 변환
        byte b = 10;
        int i = b;                          // 작은 자료형으로 변환

        int iNum = 20;
        float fNum = iNum;                  // 정밀한 자료형으로 변환

        double dNum;
        dNum = fNum + iNum;                 // 연산 중 자동 변환

        // 명시적 형 변환
        byte bNum = (byte)i;                // 작은 자료형으로 변환

        float fNum1 = (float)i;             // 정밀한 자료형으로 변환

        int iNum1 = (int)(fNum+iNum);       // 연산 중 변환
    }
}
